Add post about pushing images to VMWare
weldr/weldr.github.io pull request #12
Opened 2018-10-08 14:36 UTC by stefwalter

Depends on the following pull request being merged first:

 * [ ] #10

2018-10-08 16:06 UTC, bcl requested changes
Same small comments, and I guess this PR is a work in progress still.

2018-10-08 16:06 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    $ sudo sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
Permissive

2018-10-08 16:06 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    $ sudo systemctl enable --now lorax-composer
lorax-composer.socket

2018-10-08 16:06 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    XXXX
Fill in XXXX with a UUID

2018-10-08 16:06 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    XXX
Fill in XXX with a status output

2018-10-08 16:06 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +XXXX
Appears to be unfinished :)

2018-10-08 16:07 UTC, bcl commented
And a missing image:
/images/cockpit-composer-download-vmware.png

2018-10-10 11:05 UTC, VladimirSlavik commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +Click on the *Create Image* button and choose *Azure* from the dropdown
Azure?

2018-10-10 11:06 UTC, VladimirSlavik commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +![Create Image AMI](/images/cockpit-composer-create-vmware.png)
AMI?

2018-10-10 12:14 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    $ sudo sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
Fixed.

2018-10-10 12:14 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    $ sudo systemctl enable --now lorax-composer
Fixed.

2018-10-10 12:14 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    XXXX
Completed.

2018-10-10 12:14 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +    XXX
Completed

2018-10-10 12:15 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +![Create Image AMI](/images/cockpit-composer-create-vmware.png)
Fixed.

2018-10-10 12:15 UTC, stefwalter commented
@VladimirSlavik  @bcl I've completed this document. There is currently no way to use Composer UI (in Cockpit) to accomplish this task (due to the need to add a root password to the image). So I've removed that section.

2018-10-10 23:14 UTC, bcl approved these changes
Looks fine other than the 1 suggestion.

2018-10-10 23:14 UTC, bcl commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +
We should probably also tell them they can set a ssh key here with key = "..."

2018-10-11 06:25 UTC, stefwalter commented on _posts/2018-10-08-Pushing-Images-to-VMWare.md
> +
Done.

2018-10-14 06:14 UTC, stefwalter commented
Rebased.

2018-10-15 15:50 UTC, merged