Post about how to run Composer on RHEL
weldr/weldr.github.io pull request #16
Opened 2018-10-18 12:23 UTC by stefwalter

Composer doesn't actually work with RHEL content unless you mirror
the content repository. Anaconda has this same problem, but it's
less pronounced because it has a DVD (yay the 90's to the rescue).

2018-10-18 17:19 UTC, stefwalter commented
@snbueno Could you review this? Without it Composer fundamentally doesn't work on RHEL. Thank you.

2018-10-19 09:42 UTC, larskarlitski requested changes
Thanks!

2018-10-19 09:42 UTC, larskarlitski commented on _posts/2018-10-18-Running-Composer-on-RHEL.md
> +    $ sudo yum lorax-composer cockpit-composer cockpit composer-cli
```suggestion
    $ sudo yum install lorax-composer cockpit-composer cockpit composer-cli
```

2018-10-19 13:03 UTC, snbueno approved these changes

2018-10-19 13:04 UTC, merged